from models import Person, Movie


keanu = Person(name="Keanu Reeves", born=1964).save()
carrie = Person(name="Carrie-Anne Moss", born=1967).save()
laurence = Person(name="Laurence Fishburne", born=1961).save()
hugo = Person(name="Hugo Weaving", born=1960).save()
lillyw = Person(name="Lilly Wachowski", born=1967).save()
lanaw = Person(name="Lana Wachowski", born=1965).save()
joels = Person(name="Joel Silver", born=1952).save()

the_matrix = Movie(title="The Matrix", released=1999, tagline="Welcome to the Real World").save()
keanu.acted_in.connect(the_matrix, {'roles': ['Neo']})
carrie.acted_in.connect(the_matrix, {'roles': ['Trinity']})
laurence.acted_in.connect(the_matrix, {'roles': ['Morpheus']})
hugo.acted_in.connect(the_matrix, {'roles': ['Agent Smith']})
lillyw.directed.connect(the_matrix)
lanaw.directed.connect(the_matrix)
joels.produced.connect(the_matrix)

emil = Person(name="Emil Eifrem", born=1978).save()
emil.acted_in.connect(the_matrix, {'roles': ['Emil']})
the_matrix_reloaded = Movie(title="The Matrix Reloaded", released=2003, tagline="Free your mind").save()
keanu.acted_in.connect(the_matrix_reloaded, {'roles': ['Neo']})
carrie.acted_in.connect(the_matrix_reloaded, {'roles': ['Trinity']})
laurence.acted_in.connect(the_matrix_reloaded, {'roles': ['Morpheus']})
hugo.acted_in.connect(the_matrix_reloaded, {'roles': ['Agent Smith']})
lillyw.directed.connect(the_matrix_reloaded)
lanaw.directed.connect(the_matrix_reloaded)
joels.produced.connect(the_matrix_reloaded)

the_matrix_revolutions = Movie(title="The Matrix Revolutions", released=2003, tagline="Everything that has a beginning has an end").save()
keanu.acted_in.connect(the_matrix_revolutions, {'roles': ['Neo']})
carrie.acted_in.connect(the_matrix_revolutions, {'roles': ['Trinity']})
laurence.acted_in.connect(the_matrix_revolutions, {'roles': ['Morpheus']})
hugo.acted_in.connect(the_matrix_revolutions, {'roles': ['Agent Smith']})
lillyw.directed.connect(the_matrix_revolutions)
lanaw.directed.connect(the_matrix_revolutions)
joels.produced.connect(the_matrix_revolutions)

the_devils_advocate = Movie(title="The Devil's Advocate", released=1997, tagline="Evil has its winning ways").save()
charlize = Person(name='Charlize Theron', born=1975).save()
al = Person(name='Al Pacino', born=1940).save()
taylor = Person(name='Taylor Hackford', born=1944).save()
keanu.acted_in.connect(the_devils_advocate, {'roles': ['Kevin Lomax']})
charlize.acted_in.connect(the_devils_advocate, {'roles': ['Mary Ann Lomax']})
al.acted_in.connect(the_devils_advocate, {'roles': ['John Milton']})
taylor.directed.connect(the_devils_advocate)

a_few_good_men = Movie(title="A Few Good Men", released=1992, tagline="In the heart of the nation's capital, in a courthouse of the U.S. government, one man will stop at nothing to keep his honor, and one will stop at nothing to find the truth.").save()
tomc = Person(name='Tom Cruise', born=1962).save()
jackn = Person(name='Jack Nicholson', born=1937).save()
demim = Person(name='Demi Moore', born=1962).save()
kevinb = Person(name='Kevin Bacon', born=1958).save()
kiefers = Person(name='Kiefer Sutherland', born=1966).save()
noahw = Person(name='Noah Wyle', born=1971).save()
cubag = Person(name='Cuba Gooding Jr.', born=1968).save()
kevinp = Person(name='Kevin Pollak', born=1957).save()
jtw = Person(name='J.T. Walsh', born=1943).save()
jamesm = Person(name='James Marshall', born=1967).save()
christopherg = Person(name='Christopher Guest', born=1948).save()
robr = Person(name='Rob Reiner', born=1947).save()
aarons = Person(name='Aaron Sorkin', born=1961).save()
tomc.acted_in.connect(a_few_good_men, {'roles': ['Lt. Daniel Kaffee']})
jackn.acted_in.connect(a_few_good_men, {'roles': ['Col. Nathan R. Jessup']})
demim.acted_in.connect(a_few_good_men, {'roles': ['Lt. Cdr. JoAnne Galloway']})
kevinb.acted_in.connect(a_few_good_men, {'roles': ['Capt. Jack Ross']})
kiefers.acted_in.connect(a_few_good_men, {'roles': ['Lt. Jonathan Kendrick']})
noahw.acted_in.connect(a_few_good_men, {'roles': ['Cpl. Jeffrey Barnes']})
cubag.acted_in.connect(a_few_good_men, {'roles': ['Cpl. Carl Hammaker']})
kevinp.acted_in.connect(a_few_good_men, {'roles': ['Lt. Sam Weinberg']})
jtw.acted_in.connect(a_few_good_men, {'roles': ['Lt. Col. Matthew Andrew Markinson']})
jamesm.acted_in.connect(a_few_good_men, {'roles': ['Pfc. Louden Downey']})
christopherg.acted_in.connect(a_few_good_men, {'roles': ['Dr. Stone']})
aarons.acted_in.connect(a_few_good_men, {'roles': ['Man in Bar']})
robr.directed.connect(a_few_good_men)
aarons.wrote.connect(a_few_good_men)

top_gun = Movie(title="Top Gun", released=1986, tagline="I feel the need, the need for speed.").save()
kelly_mcGillis = Person(name='Kelly McGillis', born=1957).save()
val_kilmer = Person(name='Val Kilmer', born=1959).save()
anthony_edwards = Person(name='Anthony Edwards', born=1962).save()
tom_skerritt = Person(name='Tom Skerritt', born=1933).save()
meg_ryan = Person(name='Meg Ryan', born=1961).save()
tony_scott = Person(name='Tony Scott', born=1944).save()
jim_cash = Person(name='Jim Cash', born=1941).save()
tomc.acted_in.connect(top_gun, {'roles': ['Maverick']})
kelly_mcGillis.acted_in.connect(top_gun, {'roles': ['Charlie']})
val_kilmer.acted_in.connect(top_gun, {'roles': ['Iceman']})
anthony_edwards.acted_in.connect(top_gun, {'roles': ['Goose']})
tom_skerritt.acted_in.connect(top_gun, {'roles': ['Viper']})
meg_ryan.acted_in.connect(top_gun, {'roles': ['Carole']})
tony_scott.directed.connect(top_gun)
jim_cash.wrote.connect(top_gun)

jerry_maguire = Movie(title='Jerry Maguire', released=2000, tagline='The rest of his life begins now.').save()
renee_zellweger = Person(name='Renee Zellweger', born=1969).save()
kelly_preston = Person(name='Kelly Preston', born=1962).save()
jerry_oconnell = Person(name="Jerry O'Connell", born=1974).save()
jay_mohr = Person(name='Jay Mohr', born=1970).save()
bonnie_hunt = Person(name='Bonnie Hunt', born=1961).save()
regina_king = Person(name='Regina King', born=1971).save()
jonathan_lipnicki = Person(name='Jonathan Lipnicki', born=1996).save()
cameron_crowe = Person(name='Cameron Crowe', born=1957).save()
tomc.acted_in.connect(jerry_maguire, {'roles': ['Jerry Maguire']})
cubag.acted_in.connect(jerry_maguire, {'roles': ['Rod Tidwell']})
renee_zellweger.acted_in.connect(jerry_maguire, {'roles': ['Dorothy Boyd']})
kelly_preston.acted_in.connect(jerry_maguire, {'roles': ['Avery Bishop']})
jerry_oconnell.acted_in.connect(jerry_maguire, {'roles': ['Frank Cushman']})
jay_mohr.acted_in.connect(jerry_maguire, {'roles': ['Bob Sugar']})
bonnie_hunt.acted_in.connect(jerry_maguire, {'roles': ['Laurel Boyd']})
regina_king.acted_in.connect(jerry_maguire, {'roles': ['Marcee Tidwell']})
jonathan_lipnicki.acted_in.connect(jerry_maguire, {'roles': ['Ray Boyd']})
cameron_crowe.directed.connect(jerry_maguire)
cameron_crowe.produced.connect(jerry_maguire)
cameron_crowe.wrote.connect(jerry_maguire)

stand_by_me = Movie(title="Stand By Me", released=1986, tagline="For some, it's the last real taste of innocence, and the first real taste of life. But for everyone, it's the time that memories are made of.").save()
river_phoenix = Person(name='River Phoenix', born=1970).save()
corey_feldman = Person(name='Corey Feldman', born=1971).save()
wil_wheaton = Person(name='Wil Wheaton', born=1972).save()
john_cusack = Person(name='John Cusack', born=1966).save()
marshall_bell = Person(name='Marshall Bell', born=1942).save()
wil_wheaton.acted_in.connect(stand_by_me, {'roles': ['Gordie Lachance']})
river_phoenix.acted_in.connect(stand_by_me, {'roles': ['Chris Chambers']})
jerry_oconnell.acted_in.connect(stand_by_me, {'roles': ['Vern Tessio']})
corey_feldman.acted_in.connect(stand_by_me, {'roles': ['Teddy Duchamp']})
john_cusack.acted_in.connect(stand_by_me, {'roles': ['Denny Lachance']})
kiefers.acted_in.connect(stand_by_me, {'roles': ['Ace Merrill']})
marshall_bell.acted_in.connect(stand_by_me, {'roles': ['Mr. Lachance']})
robr.directed.connect(stand_by_me)

as_good_as_it_gets = Movie(title='As Good as It Gets', released=1997, tagline='A comedy from the heart that goes for the throat.').save()
helen_hunt = Person(name='Helen Hunt', born=1963).save()
greg_kinnear = Person(name='Greg Kinnear', born=1963).save()
james_brooks = Person(name='James L. Brooks', born=1940).save()
jackn.acted_in.connect(as_good_as_it_gets, {'roles': ['Melvin Udall']})
helen_hunt.acted_in.connect(as_good_as_it_gets, {'roles': ['Carol Connelly']})
greg_kinnear.acted_in.connect(as_good_as_it_gets, {'roles': ['Simon Bishop']})
cubag.acted_in.connect(as_good_as_it_gets, {'roles': ['Frank Sachs']})
james_brooks.directed.connect(as_good_as_it_gets)

what_dreams_may_come = Movie(title='What Dreams May Come', released=1998, tagline='After life there is more. The end is just the beginning.').save()
annabella_sciorra = Person(name='Annabella Sciorra', born=1960).save()
max_von_sydow = Person(name='Max von Sydow', born=1929).save()
werner_herzog = Person(name='Werner Herzog', born=1942).save()
robin_williams = Person(name='Robin Williams', born=1951).save()
vincent_ward = Person(name='Vincent Ward', born=1956).save()
robin_williams.acted_in.connect(what_dreams_may_come, {'roles': ['Chris Nielsen']})
cubag.acted_in.connect(what_dreams_may_come, {'roles': ['Albert Lewis']})
annabella_sciorra.acted_in.connect(what_dreams_may_come, {'roles': ['Annie Collins-Nielsen']})
max_von_sydow.acted_in.connect(what_dreams_may_come, {'roles': ['The Tracker']})
werner_herzog.acted_in.connect(what_dreams_may_come, {'roles': ['The Face']})
vincent_ward.directed.connect(what_dreams_may_come)

snow_falling_on_cedars = Movie(title='Snow Falling on Cedars', released=1999, tagline='First loves last. Forever.').save()
ethan_hawke = Person(name='Ethan Hawke', born=1970).save()
rick_yune = Person(name='Rick Yune', born=1971).save()
james_cromwell = Person(name='James Cromwell', born=1940).save()
scott_hicks = Person(name='Scott Hicks', born=1953).save()
ethan_hawke.acted_in.connect(snow_falling_on_cedars, {'roles': ['Ishmael Chambers']})
rick_yune.acted_in.connect(snow_falling_on_cedars, {'roles': ['Kazuo Miyamoto']})
max_von_sydow.acted_in.connect(snow_falling_on_cedars, {'roles': ['Nels Gudmundsson']})
james_cromwell.acted_in.connect(snow_falling_on_cedars, {'roles': ['Judge Fielding']})
scott_hicks.directed.connect(snow_falling_on_cedars)

youve_got_mail = Movie(title="You've Got Mail", released=1998, tagline='At odds in life.. in love on-line.').save()
parker_posey = Person(name='Parker Posey', born=1968).save()
dave_chappelle = Person(name='Dave Chappelle', born=1973).save()
steve_zahn = Person(name='Steve Zahn', born=1967).save()
tom_hanks = Person(name='Tom Hanks', born=1956).save()
nora_ephron = Person(name='Nora Ephron', born=1941).save()
tom_hanks.acted_in.connect(youve_got_mail, {'roles': ['Joe Fox']})
meg_ryan.acted_in.connect(youve_got_mail, {'roles': ['Kathleen Kelly']})
greg_kinnear.acted_in.connect(youve_got_mail, {'roles': ['Frank Navasky']})
parker_posey.acted_in.connect(youve_got_mail, {'roles': ['Patricia Eden']})
dave_chappelle.acted_in.connect(youve_got_mail, {'roles': ['Kevin Jackson']})
steve_zahn.acted_in.connect(youve_got_mail, {'roles': ['George Pappas']})
nora_ephron.directed.connect(youve_got_mail)

sleepless_in_seattle = Movie(title='Sleepless in Seattle', released=1993, tagline="What if someone you never met, someone you never saw, someone you never knew was the only someone for you?").save()
rita_wilson = Person(name='Rita Wilson', born=1956).save()
bill_pullman = Person(name='Bill Pullman', born=1953).save()
victor_garber = Person(name='Victor Garber', born=1949).save()
rosie_odonnell = Person(name="Rosie O'Donnell", born=1962).save()
tom_hanks.acted_in.connect(sleepless_in_seattle, {'roles': ['Sam Baldwin']})
meg_ryan.acted_in.connect(sleepless_in_seattle, {'roles': ['Annie Reed']})
rita_wilson.acted_in.connect(sleepless_in_seattle, {'roles': ['Suzy']})
bill_pullman.acted_in.connect(sleepless_in_seattle, {'roles': ['Walter']})
victor_garber.acted_in.connect(sleepless_in_seattle, {'roles': ['Greg']})
rosie_odonnell.acted_in.connect(sleepless_in_seattle, {'roles': ['Becky']})
nora_ephron.directed.connect(sleepless_in_seattle)

joe_versus_the_volcano = Movie(title='Joe Versus the Volcano', released=1990, tagline='A story of love, lava and burning desire.').save()
john_patrick_stanley = Person(name='John Patrick Stanley', born=1950).save()
nathan_lane = Person(name='Nathan Lane', born=1956).save()
tom_hanks.acted_in.connect(joe_versus_the_volcano, {'roles': ['Joe Banks']})
meg_ryan.acted_in.connect(joe_versus_the_volcano, {'roles': ['DeDe', 'Angelica Graynamore', 'Patricia Graynamore']})
nathan_lane.acted_in.connect(joe_versus_the_volcano, {'roles': ['Baw']})
john_patrick_stanley.directed.connect(joe_versus_the_volcano)

when_harry_met_sally = Movie(title='When Harry Met Sally', released=1998, tagline='Can two friends sleep together and still love each other in the morning?').save()
billy_crystal = Person(name='Billy Crystal', born=1948).save()
carrie_fisher = Person(name='Carrie Fisher', born=1956).save()
bruno_kirby = Person(name='Bruno Kirby', born=1949).save()
billy_crystal.acted_in.connect(when_harry_met_sally, {'roles': ['Harry Burns']})
meg_ryan.acted_in.connect(when_harry_met_sally, {'roles': ['Sally Albright']})
carrie_fisher.acted_in.connect(when_harry_met_sally, {'roles': ['Marie']})
bruno_kirby.acted_in.connect(when_harry_met_sally, {'roles': ['Jess']})
robr.directed.connect(when_harry_met_sally)
robr.produced.connect(when_harry_met_sally)
nora_ephron.produced.connect(when_harry_met_sally)
nora_ephron.wrote.connect(when_harry_met_sally)

that_thing_you_do = Movie(title='That Thing You Do', released=1996, tagline='In every life there comes a time when that thing you dream becomes that thing you do').save()
liv_tyler = Person(name='Liv Tyler', born=1977).save()
tom_hanks.acted_in.connect(that_thing_you_do, {'roles': ['Mr. White']})
liv_tyler.acted_in.connect(that_thing_you_do, {'roles': ['Faye Dolan']})
charlize.acted_in.connect(that_thing_you_do, {'roles': ['Tina']})
tom_hanks.directed.connect(that_thing_you_do)

the_replacements = Movie(title='The Replacements', released=2000, tagline='Pain heals, Chicks dig scars.. Glory lasts forever').save()
brooke_langton = Person(name='Brooke Langton', born=1970).save()
gene_hackman = Person(name='Gene Hackman', born=1930).save()
orlando_jones = Person(name='Orlando Jones', born=1968).save()
howard_deutch = Person(name='Howard Deutch', born=1950).save()
keanu.acted_in.connect(the_replacements, {'roles': ['Shane Falco']})
brooke_langton.acted_in.connect(the_replacements, {'roles': ['Annabelle Farrell']})
gene_hackman.acted_in.connect(the_replacements, {'roles': ['Jimmy McGinty']})
orlando_jones.acted_in.connect(the_replacements, {'roles': ['Clifford Franklin']})
howard_deutch.directed.connect(the_replacements)

rescue_dawn = Movie(title='Rescue Dawn', released=2006, tagline="Based on the extraordinary true story of one man's fight for freedom").save()
christian_bale = Person(name='Christian Bale', born=1974).save()
zach_grenier = Person(name='Zach Grenier', born=1954).save()
marshall_bell.acted_in.connect(rescue_dawn, {'roles': ['Admiral']})
christian_bale.acted_in.connect(rescue_dawn, {'roles': ['Dieter Dengler']})
zach_grenier.acted_in.connect(rescue_dawn, {'roles': ['Squad Leader']})
steve_zahn.acted_in.connect(rescue_dawn, {'roles': ['Duane']})
werner_herzog.directed.connect(rescue_dawn)

the_birdcage = Movie(title='The Birdcage', released=1996, tagline='Come as you are').save()
mike_nichols = Person(name='Mike Nichols', born=1931).save()
robin_williams.acted_in.connect(the_birdcage, {'roles': ['Armand Goldman']})
nathan_lane.acted_in.connect(the_birdcage, {'roles': ['Albert Goldman']})
gene_hackman.acted_in.connect(the_birdcage, {'roles': ['Sen. Kevin Keeley']})
mike_nichols.directed.connect(the_birdcage)

unforgiven = Movie(title='Unforgiven', released=1992, tagline="It's a hell of a thing, killing a man").save()
richard_harris = Person(name='Richard Harris', born=1930).save()
clint_eastwood = Person(name='Clint Eastwood', born=1930).save()
richard_harris.acted_in.connect(unforgiven, {'roles': ['English Bob']})
clint_eastwood.acted_in.connect(unforgiven, {'roles': ['Bill Munny']})
gene_hackman.acted_in.connect(unforgiven, {'roles': ['Little Bill Daggett']})
clint_eastwood.directed.connect(unforgiven)

johnny_mnemonic = Movie(title='Johnny Mnemonic', released=1995, tagline='The hottest data on earth. In the coolest head in town').save()
takeshi_kitano = Person(name='Takeshi Kitano', born=1947).save()
dina_meyer = Person(name='Dina Meyer', born=1968).save()
ice_t = Person(name='Ice-T', born=1958).save()
robert_longo = Person(name='Robert Longo', born=1953).save()
keanu.acted_in.connect(johnny_mnemonic, {'roles': ['Johnny Mnemonic']})
takeshi_kitano.acted_in.connect(johnny_mnemonic, {'roles': ['Takahashi']})
dina_meyer.acted_in.connect(johnny_mnemonic, {'roles': ['Jane']})
ice_t.acted_in.connect(johnny_mnemonic, {'roles': ['J-Bone']})
robert_longo.directed.connect(johnny_mnemonic)

cloud_atlas = Movie(title='Cloud Atlas', released=2012, tagline='Everything is connected').save()
halle_berry = Person(name='Halle Berry', born=1966).save()
jim_broadbent = Person(name='Jim Broadbent', born=1949).save()
tom_tykwer = Person(name='Tom Tykwer', born=1965).save()
david_mitchell = Person(name='David Mitchell', born=1969).save()
stefan_arndt = Person(name='Stefan Arndt', born=1961).save()
tom_hanks.acted_in.connect(cloud_atlas, {'roles': ['Zachry', 'Dr. Henry Goose', 'Isaac Sachs', 'Dermot Hoggins']})
hugo.acted_in.connect(cloud_atlas, {'roles': ['Bill Smoke', 'Haskell Moore', 'Tadeusz Kesselring', 'Nurse Noakes', 'Boardman Mephi', 'Old Georgie']})
halle_berry.acted_in.connect(cloud_atlas, {'roles': ['Luisa Rey', 'Jocasta Ayrs', 'Ovid', 'Meronym']})
jim_broadbent.acted_in.connect(cloud_atlas, {'roles': ['Vyvyan Ayrs', 'Captain Molyneux', 'Timothy Cavendish']})
tom_tykwer.directed.connect(cloud_atlas)
lillyw.directed.connect(cloud_atlas)
lanaw.directed.connect(cloud_atlas)
david_mitchell.wrote.connect(cloud_atlas)
stefan_arndt.produced.connect(cloud_atlas)

the_da_vinci_code = Movie(title='The Da Vinci Code', released=2006, tagline='Break The Codes').save()
ian_mckellen = Person(name='Ian McKellen', born=1939).save()
audrey_tautou = Person(name='Audrey Tautou', born=1976).save()
paul_bettany = Person(name='Paul Bettany', born=1971).save()
ron_howard = Person(name='Ron Howard', born=1954).save()
tom_hanks.acted_in.connect(the_da_vinci_code, {'roles': ['Dr. Robert Langdon']})
ian_mckellen.acted_in.connect(the_da_vinci_code, {'roles': ['Sir Leight Teabing']})
audrey_tautou.acted_in.connect(the_da_vinci_code, {'roles': ['Sophie Neveu']})
paul_bettany.acted_in.connect(the_da_vinci_code, {'roles': ['Silas']})
ron_howard.directed.connect(the_da_vinci_code)

v_for_vendetta = Movie(title='V for Vendetta', released=2006, tagline='Freedom! Forever!').save()
natalie_portman = Person(name='Natalie Portman', born=1981).save()
stephen_rea = Person(name='Stephen Rea', born=1946).save()
john_hurt = Person(name='John Hurt', born=1940).save()
ben_miles = Person(name='Ben Miles', born=1967).save()
hugo.acted_in.connect(v_for_vendetta, {'roles': ['V']})
natalie_portman.acted_in.connect(v_for_vendetta, {'roles': ['Evey Hammond']})
stephen_rea.acted_in.connect(v_for_vendetta, {'roles': ['Eric Finch']})
john_hurt.acted_in.connect(v_for_vendetta, {'roles': ['High Chancellor Adam Sutler']})
ben_miles.acted_in.connect(v_for_vendetta, {'roles': ['Dascomb']})
jamesm.directed.connect(v_for_vendetta)
lillyw.produced.connect(v_for_vendetta)
lanaw.produced.connect(v_for_vendetta)
joels.produced.connect(v_for_vendetta)
lillyw.wrote.connect(v_for_vendetta)
lanaw.wrote.connect(v_for_vendetta)

speed_racer = Movie(title='Speed Racer', released=2008, tagline='Speed has no limits').save()
emile_hirsch = Person(name='Emile Hirsch', born=1985).save()
john_goodman = Person(name='John Goodman', born=1960).save()
susan_sarandon = Person(name='Susan Sarandon', born=1946).save()
matthew_fox = Person(name='Matthew Fox', born=1966).save()
christina_ricci = Person(name='Christina Ricci', born=1980).save()
rain = Person(name='Rain', born=1982).save()
emile_hirsch.acted_in.connect(speed_racer, {'roles': ['Speed Racer']})
john_goodman.acted_in.connect(speed_racer, {'roles': ['Pops']})
susan_sarandon.acted_in.connect(speed_racer, {'roles': ['Mom']})
matthew_fox.acted_in.connect(speed_racer, {'roles': ['Racer X']})
christina_ricci.acted_in.connect(speed_racer, {'roles': ['Trixie']})
rain.acted_in.connect(speed_racer, {'roles': ['Taejo Togokahn']})
ben_miles.acted_in.connect(speed_racer, {'roles': ['Cass Jones']})
lillyw.directed.connect(speed_racer)
lanaw.directed.connect(speed_racer)
lillyw.wrote.connect(speed_racer)
lanaw.wrote.connect(speed_racer)
joels.produced.connect(speed_racer)

ninja_assassin = Movie(title='Ninja Assassin', released=2009, tagline='Prepare to enter a secret world of assassins').save()
naomie_harris = Person(name='Naomie Harris').save()
rain.acted_in.connect(ninja_assassin, {'roles': ['Raizo']})
naomie_harris.acted_in.connect(ninja_assassin, {'roles': ['Mika Coretti']})
rick_yune.acted_in.connect(ninja_assassin, {'roles': ['Takeshi']})
ben_miles.acted_in.connect(ninja_assassin, {'roles': ['Ryan Maslow']})
jamesm.directed.connect(ninja_assassin)
lillyw.produced.connect(ninja_assassin)
lanaw.produced.connect(ninja_assassin)
joels.produced.connect(ninja_assassin)

the_green_mile = Movie(title='The Green Mile', released=1999, tagline="Walk a mile you'll never forget.").save()
michael_clarke_duncan = Person(name='Michael Clarke Duncan', born=1957).save()
david_morse = Person(name='David Morse', born=1953).save()
sam_rockwell = Person(name='Sam Rockwell', born=1968).save()
gary_sinise = Person(name='Gary Sinise', born=1955).save()
patricia_clarkson = Person(name='Patricia Clarkson', born=1959).save()
frank_darabont = Person(name='Frank Darabont', born=1959).save()
tom_hanks.acted_in.connect(the_green_mile, {'roles': ['Paul Edgecomb']})
michael_clarke_duncan.acted_in.connect(the_green_mile, {'roles': ['John Coffey']})
david_morse.acted_in.connect(the_green_mile, {'roles': ['Brutus "Brutal" Howell']})
bonnie_hunt.acted_in.connect(the_green_mile, {'roles': ['Jan Edgecomb']})
james_cromwell.acted_in.connect(the_green_mile, {'roles': ['Warden Hal Moores']})
sam_rockwell.acted_in.connect(the_green_mile, {'roles': ['"Wild Bill" Wharton']})
gary_sinise.acted_in.connect(the_green_mile, {'roles': ['Burt Hammersmith']})
patricia_clarkson.acted_in.connect(the_green_mile, {'roles': ['Melinda Moores']})
frank_darabont.directed.connect(the_green_mile)

frost_nixon = Movie(title='Frost/Nixon', released=2008, tagline='400 million people were waiting for the truth.').save()
frank_langella = Person(name='Frank Langella', born=1938).save()
michael_sheen = Person(name='Michael Sheen', born=1969).save()
oliver_platt = Person(name='Oliver Platt', born=1960).save()
frank_langella.acted_in.connect(frost_nixon, {'roles': ['Richard Nixon']})
michael_sheen.acted_in.connect(frost_nixon, {'roles': ['David Frost']})
kevinb.acted_in.connect(frost_nixon, {'roles': ['Jack Brennan']})
oliver_platt.acted_in.connect(frost_nixon, {'roles': ['Bob Zelnick']})
sam_rockwell.acted_in.connect(frost_nixon, {'roles': ['James Reston, Jr.']})
ron_howard.directed.connect(frost_nixon)

hoffa = Movie(title='Hoffa', released=1992, tagline="He didn't want law. He wanted justice.").save()
danny_devito = Person(name='Danny DeVito', born=1944).save()
john_c_reilly = Person(name='John C. Reilly', born=1965).save()
jackn.acted_in.connect(hoffa, {'roles': ['Hoffa']})
danny_devito.acted_in.connect(hoffa, {'roles': ['Robert "Bobby" Ciaro']})
danny_devito.directed.connect(hoffa)
jtw.acted_in.connect(hoffa, {'roles': ['Frank Fitzsimmons']})
john_c_reilly.acted_in.connect(hoffa, {'roles': ['Peter "Pete" Connelly']})

apollo_13 = Movie(title='Apollo 13', released=1995, tagline='Houston, we have a problem.').save()
ed_harris = Person(name='Ed Harris', born=1950).save()
bill_paxton = Person(name='Bill Paxton', born=1955).save()
tom_hanks.acted_in.connect(apollo_13, {'roles': ['Jim Lovell']})
kevinb.acted_in.connect(apollo_13, {'roles': ['Jack Swigert']})
ed_harris.acted_in.connect(apollo_13, {'roles': ['Gene Kranz']})
bill_paxton.acted_in.connect(apollo_13, {'roles': ['Fred Haise']})
gary_sinise.acted_in.connect(apollo_13, {'roles': ['Ken Mattingly']})
ron_howard.directed.connect(apollo_13)

twister = Movie(title='Twister', released=1996, tagline="Don't Breathe. Don't Look Back.").save()
philip_seymour_hoffman = Person(name='Philip Seymour Hoffman', born=1967).save()
jan_de_bont = Person(name='Jan de Bont', born=1943).save()
bill_paxton.acted_in.connect(twister, {'roles': ['Bill Harding']})
helen_hunt.acted_in.connect(twister, {'roles': ['Dr. Jo Harding']})
zach_grenier.acted_in.connect(twister, {'roles': ['Eddie']})
philip_seymour_hoffman.acted_in.connect(twister, {'roles': ['Dustin "Dusty" Davis']})
jan_de_bont.directed.connect(twister)

cast_away = Movie(title='Cast Away', released=2000, tagline='At the edge of the world, his journey begins.').save()
robert_zemeckis = Person(name='Robert Zemeckis', born=1951).save()
tom_hanks.acted_in.connect(cast_away, {'roles': ['Chuck Noland']})
helen_hunt.acted_in.connect(cast_away, {'roles': ['Kelly Frears']})
robert_zemeckis.directed.connect(cast_away)

one_flew_over_the_cuckoos_nest = Movie(title="One Flew Over the Cuckoo's Nest", released=1975, tagline="If he's crazy, what does that make you?").save()
milos_forman = Person(name='Milos Forman', born=1932).save()
jackn.acted_in.connect(one_flew_over_the_cuckoos_nest, {'roles': ['Randle McMurphy']})
danny_devito.acted_in.connect(one_flew_over_the_cuckoos_nest, {'roles': ['Martini']})
milos_forman.directed.connect(one_flew_over_the_cuckoos_nest)

somethings_gotta_give = Movie(title="Something's Gotta Give", released=2003).save()
diane_keaton = Person(name='Diane Keaton', born=1946).save()
nancy_meyers = Person(name='Nancy Meyers', born=1949).save()
jackn.acted_in.connect(somethings_gotta_give, {'roles': ['Harry Sanborn']})
diane_keaton.acted_in.connect(somethings_gotta_give, {'roles': ['Erica Barry']})
keanu.acted_in.connect(somethings_gotta_give, {'roles': ['Julian Mercer']})
nancy_meyers.directed.connect(somethings_gotta_give)
nancy_meyers.produced.connect(somethings_gotta_give)
nancy_meyers.wrote.connect(somethings_gotta_give)

bicentennial_man = Movie(title='Bicentennial Man', released=1999, tagline="One robot's 200 year journey to become an ordinary man").save()
chris_columbus = Person(name='Chris Columbus', born=1958).save()
robin_williams.acted_in.connect(bicentennial_man, {'roles': ['Andrew Marin']})
oliver_platt.acted_in.connect(bicentennial_man, {'roles': ['Rupert Burns']})
chris_columbus.directed.connect(bicentennial_man)

charlie_wilsons_war = Movie(title="Charlie Wilson's War", released=2007, tagline="A stiff drink. A little mascara. A lot of nerve. Who said they couldn't bring down the Soviet empire.").save()
julia_roberts = Person(name='Julia Roberts', born=1967).save()
tom_hanks.acted_in.connect(charlie_wilsons_war, {'roles': ['Rep. Charlie Wilson']})
julia_roberts.acted_in.connect(charlie_wilsons_war, {'roles': ['Joanne Herring']})
philip_seymour_hoffman.acted_in.connect(charlie_wilsons_war, {'roles': ['Gust Avrakotos']})
mike_nichols.directed.connect(charlie_wilsons_war)

the_polar_express = Movie(title='The Polar Express', released=2004, tagline='This Holiday Season.. Believe').save()
tom_hanks.acted_in.connect(the_polar_express, {'roles': ['Hero Boy', 'Father', 'Conductor', 'Hobo', 'Scrooge', 'Santa Claus']})
robert_zemeckis.directed.connect(the_polar_express)

a_league_of_their_own = Movie(title='A League of Their Own', released=1992, tagline='Once in a lifetime you get a chance to do something different.').save()
madonna = Person(name='Madonna', born=1954).save()
geena_davis = Person(name='Geena Davis', born=1956).save()
lori_petty = Person(name='Lori Petty', born=1963).save()
penny_marshall = Person(name='Penny Marshall', born=1943).save()
tom_hanks.acted_in.connect(a_league_of_their_own, {'roles': ['Jimmy Dugan']})
geena_davis.acted_in.connect(a_league_of_their_own, {'roles': ['Dottie Hinson']})
lori_petty.acted_in.connect(a_league_of_their_own, {'roles': ['Kit Keller']})
rosie_odonnell.acted_in.connect(a_league_of_their_own, {'roles': ['Doris Murphy']})
madonna.acted_in.connect(a_league_of_their_own, {'roles': ['"All the Way" Mae Mordabito']})
bill_paxton.acted_in.connect(a_league_of_their_own, {'roles': ['Bob Hinson']})
penny_marshall.directed.connect(a_league_of_their_own)

paul_blythe = Person(name='Paul Blythe').save()
angela_scope = Person(name='Angela Scope').save()
jessica_thompson = Person(name='Jessica Thompson').save()
james_thompson = Person(name='James Thompson').save()
james_thompson.follows.connect(jessica_thompson)
angela_scope.follows.connect(jessica_thompson)
paul_blythe.follows.connect(angela_scope)

jessica_thompson.reviewed.connect(cloud_atlas, {'summary': 'An amazing journey', 'rating': 95})
jessica_thompson.reviewed.connect(the_replacements, {'summary': 'Silly, but fun', 'rating': 65})
jessica_thompson.reviewed.connect(unforgiven, {'summary': 'Dark, but compelling', 'rating': 85})
jessica_thompson.reviewed.connect(the_birdcage, {'summary': "Slapstick redeemed only by the Robin Williams and Gene Hackman's stellar performances", 'rating': 45})
jessica_thompson.reviewed.connect(the_da_vinci_code, {'summary': 'A solid romp', 'rating': 68})
jessica_thompson.reviewed.connect(jerry_maguire, {'summary': 'You had me at Jerry', 'rating': 92})
james_thompson.reviewed.connect(the_replacements, {'summary': 'The coolest football movie ever', 'rating': 100})
james_thompson.reviewed.connect(the_da_vinci_code, {'summary': 'Fun, but a little far fetched', 'rating': 65})
angela_scope.reviewed.connect(the_replacements, {'summary': 'Pretty funny at times', 'rating': 62})

# Query all movies and directors that Tom Hanks acted in, limited in 10
results = []
for movie in tom_hanks.acted_in.all():
    directors = movie.directors.all()
    results.append((tom_hanks, movie, directors))

results = results[:10]
print(results)