version: "3.2"
services:
  neo4j:
    image: neo4j:latest
    volumes:
      - '$HOME/neo4j/data:/data'
      # - '$HOME/neo4j/conf/:/conf/'
    ports:
      - 7474:7474
      - 7687:7687
    restart: on-failure
    networks:
        - neo4j_python_net
    command: neo4j
    environment:
      - NEO4J_AUTH=none

networks:
  neo4j_python_net:
    driver: bridge

volumes:
  dbgraph:
